### ISSUE TITLE
services de-registering randomly 

### ISSUE THREAD

**Issue by tsmgeek** [hashicorp/consul-k8s#59]
Kubernetes Platform Version: 1.11.5 (eks.1)

I installed the consul-0.5.0 helm chart and enabled sync k8s->consul.
In the default setup services appear and disappear randomly, I am unable to see any pattern to what is happening.

There are logs such as these on startup but nothing else causing concern other than `registering services` for the most part.
```
2019-01-29T09:59:38.933Z [WARN ] to-consul/source: error loading initial endpoints: key=kafka/confluent-1-nodeport err="an empty namespace may not be set when a resource name is provided"
2019-01-29T10:00:13.564Z [INFO ] to-consul/sink: invalid service found, scheduling for delete: service-name=sentry
2019-01-29T10:32:17.364Z [WARN ] to-consul/source: error loading initial endpoints: key=testing/rocketchat err="an empty namespace may not be set when a resource name is provided"
2019-01-29T10:32:17.368Z [INFO ] to-consul/source: upsert: key=testing/rocketchat
```

I have done some checks and this is what i can see.
- services randomly disappear between "registering services" log entries
- services that have disappeared instantly show up again when "registering services" is shown
- seems it just re-registers the missing services
- happens with services that have any number of pods
- ive tested 0.3.0 and 0.4.0

**Comment by adilyse** [comment]
More details about this issue are available in #40, and it should be fixed by #63.

**Comment by josephschadlick** [comment]
I am experiencing this same issue even after upgrading to consul-k8s v0.5.0 (consul-helm v0.6.0). I can't nail down the cause. Let me know if you require additional information or if I should open a new  issue around this.

**Comment by tsmgeek** [comment]
Confirmed that I am still seeing the issue, its not as bad as before but there are still some services that are disappearing.
